siteshop/shop/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.PeopleHome.as_view(), name='home'),
    path('category/<slug:cat_slug>/',
         views.ShopCategory.as_view(), name='category'),
    path('item/<slug:item_slug>/', views.ShowItem.as_view(), name='item'),
    path('item/<slug:slug>/edit/', views.UpdateItem.as_view(), name='edit_item'),
    path('add_item/', views.AddItem.as_view(), name='add_item'),
    path('delete_item/<slug:slug>/',
         views.DeletePage.as_view(), name='delete_item'),
]

siteshop/siteshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from siteshop import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('users/', include('users.urls', namespace="users")),
    path('api-auth/', include('rest_framework.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

siteshop/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    path('delete/', views.DeleteUser.as_view(), name='delete_user'),
    path('api/v1/rules/', views.ListRulesAPI.as_view(), name='api_rules'),
    path('api/v1/rules/<int:pk>/', views.UpdateRuleAPI.as_view(),
         name='api_rule_detail'),
    path('about_api', views.AboutApi.as_view(), name='about_api')
]

siteshop/templates/includes/mainmenu.html
        <ul>
            {% if title == "Главная страница" %}
            <li><a class="selected">Главная</a></li>
            {% else %}
            <li><a href="{% url "home" %}">Главная</a></li>
            {% endif %}

            {% comment %} {% if title == "Товары" %}
            <li><a class="selected">Товары</a></li>
            {% else %}
            <li><a href="">Товары</a></li>
            {% endif %} {% endcomment %}
                {% comment %} <ul>
                    <li><a href="#">Sub menu 1</a></li>
                    <li><a href="#">Sub menu 2</a></li>
                    <li><a href="#">Sub menu 3</a></li>
              </ul> {% endcomment %}
            </li>
            {% comment %} <li><a href="about.html">About</a>
                <ul>
                    <li><a href="#">Sub menu 1</a></li>
                    <li><a href="#">Sub menu 2</a></li>
                    <li><a href="#">Sub menu 3</a></li>
                    <li><a href="#">Sub menu 4</a></li>
                    <li><a href="#">Sub menu 5</a></li>
              </ul>
            </li>
            <li><a href="faqs.html">FAQs</a></li>
            <li><a href="checkout.html">Checkout</a></li>
            <li><a href="contact.html">Contact</a></li> {% endcomment %}
            {% if user.is_authenticated %}

                {% if title == "Добавить товар" %}
                <li><a class="selected">Добавить товар</a></li>
                {% else %}
                <li><a href="{% url "add_item" %}">Добавить товар</a></li>
                {% endif %}


                {% if title == "Профиль пользователя" %}
                <li><a class="selected">Профиль | {{ user.first_name }}</a></li>
                {% else %}
                <li><a href="{% url "users:profile" %}">Профиль | {{ user.first_name }}</a></li>
                {% endif %}
                <li><a href="{% url "users:logout" %}">Выйти</a></li>

            {% else %}

            {% if title == "Авторизация" %}
            <li><a class="selected">Войти</a></li>
            {% else %}
            <li><a href="{% url "users:login" %}">Войти</a></li>
            {% endif %}

            {% if title == "Регистрация" %}
            <li><a class="selected">Регистрация</a></li>
            {% else %}
            <li><a href="{% url "users:register" %}">Регистрация</a></li>
            {% endif %}

            {% endif %}


            {% if title == "Про API" %}
            <li><a class="selected">Про API</a></li>
            {% else %}
            <li><a href="{% url "users:about_api" %}">Про API</a></li>
            {% endif %}

        </ul>
        <br style="clear: left" />